[package]
name = "affinity"
description = "Image editing and design software"
homepage = "https://www.affinity.studio/"

[version]
from = "sparkle"
repo = "https://things.seriflabs.com/affinity-update-mac-retail-studiopro"
join = "+"

[[artifact]]
match = { os = "darwin" }
url = "https://affinity-update.s3.amazonaws.com/mac2/retail/Affinity%20Affinity%20Store%20{{version_part2}}.zip"
app = ["Affinity.app"]
