[package]
name = "node"

[version]
value = "22.20.0"

[[artifact]]
match = { os = "darwin", arch = "arm64" }
url = "https://nodejs.org/dist/v{{version}}/node-v{{version}}-darwin-arm64.tar.gz"
sha256_url = "https://nodejs.org/dist/v{{version}}/SHASUMS256.txt"
strip = 1
bin = ["bin/node", "bin/npm", "bin/npx"]

[[artifact]]
match = { os = "darwin", arch = "amd64" }
url = "https://nodejs.org/dist/v{{version}}/node-v{{version}}-darwin-x64.tar.gz"
sha256_url = "https://nodejs.org/dist/v{{version}}/SHASUMS256.txt"
strip = 1
bin = ["bin/node", "bin/npm", "bin/npx"]

# The builds from nodejs.org need glibc.
[[artifact]]
match = { os = "linux", arch = "arm64", libc = "glibc" }
url = "https://nodejs.org/dist/v{{version}}/node-v{{version}}-linux-arm64.tar.gz"
sha256_url = "https://nodejs.org/dist/v{{version}}/SHASUMS256.txt"
strip = 1
bin = ["bin/node", "bin/npm", "bin/npx"]

[[artifact]]
match = { os = "linux", arch = "amd64", libc = "glibc" }
url = "https://nodejs.org/dist/v{{version}}/node-v{{version}}-linux-x64.tar.gz"
sha256_url = "https://nodejs.org/dist/v{{version}}/SHASUMS256.txt"
strip = 1
bin = ["bin/node", "bin/npm", "bin/npx"]
